<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.9.9 on darwin)" generated="20220303 15:43:59.263" rpa="false" schemaversion="2">
<suite id="s1" name="Login Scenarios" source="/Users/sumods/Desktop/wazirx-test-automation-suite-master/TestSuites/MobileApplicationTest/Login_Scenarios.robot">
<kw name="Launch App" library="Common-Keywords" type="SETUP">
<kw name="Run Keyword If" library="BuiltIn">
<arg>'${Login_Type}'=='LOCAL'</arg>
<arg>Launch WazirX Application</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="PASS" starttime="20220303 15:43:59.596" endtime="20220303 15:43:59.596"/>
</kw>
<kw name="Run Keyword If" library="BuiltIn">
<arg>'${Login_Type}'=='BROWSERSTACK'</arg>
<arg>Launch App In BrowserStack</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<kw name="Launch App In BrowserStack" library="Common-Keywords">
<kw name="Open Application" library="AppiumLibrary">
<arg>https://trupti45:9fNqHzpy9EooAfU5wqDW@hub-cloud.browserstack.com/wd/hub</arg>
<arg>realMobile=true</arg>
<arg>device=${BrowserStackDeviceName}</arg>
<arg>app=bs://d90defcbe362c2a85092d4c8552a1efc85102317</arg>
<arg>platformName=${PlatformName}</arg>
<arg>platformVersion=${PlatformVersion}</arg>
<arg>project=WazirX</arg>
<arg>build=${buildversion}</arg>
<arg>browserstack.maskCommands=setValues,getValues,setCookies,getCookies</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20220303 15:43:59.668" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /wd/hub/session</msg>
<msg timestamp="20220303 15:43:59.713" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /wd/hub/session</msg>
<msg timestamp="20220303 15:43:59.758" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20220303 15:43:59.815" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20220303 15:43:59.805" endtime="20220303 15:43:59.815"/>
</kw>
<msg timestamp="20220303 15:43:59.823" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20220303 15:43:59.834" level="FAIL">MaxRetryError: HTTPSConnectionPool(host='hub-cloud.browserstack.com', port=443): Max retries exceeded with url: /wd/hub/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))</msg>
<status status="FAIL" starttime="20220303 15:43:59.597" endtime="20220303 15:43:59.834"/>
</kw>
<status status="FAIL" starttime="20220303 15:43:59.597" endtime="20220303 15:43:59.835"/>
</kw>
<status status="FAIL" starttime="20220303 15:43:59.596" endtime="20220303 15:43:59.835"/>
</kw>
<status status="FAIL" starttime="20220303 15:43:59.595" endtime="20220303 15:43:59.836"/>
</kw>
<test id="s1-t1" name="InvalidUsernameAndPassword">
<tag>SanityTest</tag>
<status status="FAIL" starttime="20220303 15:43:59.836" endtime="20220303 15:43:59.837">Parent suite setup failed:
MaxRetryError: HTTPSConnectionPool(host='hub-cloud.browserstack.com', port=443): Max retries exceeded with url: /wd/hub/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))</status>
</test>
<kw name="Close Application" library="AppiumLibrary" type="TEARDOWN">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20220303 15:43:59.841" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20220303 15:43:59.839" endtime="20220303 15:43:59.841"/>
</kw>
<msg timestamp="20220303 15:43:59.847" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20220303 15:43:59.848" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20220303 15:43:59.838" endtime="20220303 15:43:59.848">No application is open</status>
</kw>
<status status="FAIL" starttime="20220303 15:43:59.265" endtime="20220303 15:43:59.848">Suite setup failed:
MaxRetryError: HTTPSConnectionPool(host='hub-cloud.browserstack.com', port=443): Max retries exceeded with url: /wd/hub/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

Also suite teardown failed:
No application is open</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">SanityTest</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Login Scenarios">Login Scenarios</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220303 15:43:59.342" level="WARN">Imported library '/Users/sumods/Desktop/wazirx-test-automation-suite-master/Common/Keywords/CustomLibrary.py' contains no keywords.</msg>
<msg timestamp="20220303 15:43:59.344" level="ERROR">Error in file '/Users/sumods/Desktop/wazirx-test-automation-suite-master/Common/Keywords/Common-Keywords.robot' on line 6: Importing library 'JSONLibrary' failed: ModuleNotFoundError: No module named 'JSONLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/bin
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/lib/python3.9/site-packages</msg>
<msg timestamp="20220303 15:43:59.562" level="ERROR">Error in file '/Users/sumods/Desktop/wazirx-test-automation-suite-master/~DEPENDENCIES.txt' on line 13: Importing library 'HttpLibrary.HTTP' failed: ModuleNotFoundError: No module named 'HttpLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/bin
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/lib/python3.9/site-packages</msg>
<msg timestamp="20220303 15:43:59.582" level="ERROR">Error in file '/Users/sumods/Desktop/wazirx-test-automation-suite-master/~DEPENDENCIES.txt' on line 17: Importing library 'RequestsLibrary' failed: ModuleNotFoundError: No module named 'RequestsLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/bin
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/lib/python3.9/site-packages</msg>
<msg timestamp="20220303 15:43:59.585" level="ERROR">Error in file '/Users/sumods/Desktop/wazirx-test-automation-suite-master/~DEPENDENCIES.txt' on line 18: Importing library 'ImapLibrary' failed: ModuleNotFoundError: No module named 'ImapLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/bin
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/lib/python3.9/site-packages</msg>
<msg timestamp="20220303 15:43:59.590" level="ERROR">Error in file '/Users/sumods/Desktop/wazirx-test-automation-suite-master/~DEPENDENCIES.txt' on line 21: Importing library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/bin
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/sumods/Downloads/wazirx-test-automation-suite-master/venv/lib/python3.9/site-packages</msg>
<msg timestamp="20220303 15:43:59.668" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /wd/hub/session</msg>
<msg timestamp="20220303 15:43:59.713" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /wd/hub/session</msg>
<msg timestamp="20220303 15:43:59.758" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /wd/hub/session</msg>
<msg timestamp="20220303 15:43:59.823" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20220303 15:43:59.847" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
